version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.4
Branches:
  only: 
     -  main

jobs:
#Frontend job that run both of build and test scripts and presist the project folder
  frontend_build_test :
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Installing Main dependencies
          command: |
            npm install   
      - run:
          name: Installing Frontend dependencies
          command: |
            npm run frontend:install   
      - run:
          name: Linting
          command: |
            npm run frontend:lint
      - run:
          name: App Build
          command: |
            npm run frontend:build
      - run:
          name: Frontend Tests
          command: |
            npm run frontend:test
      - persist_to_workspace:
          root: .
          paths:
            - ./*

#Backend job that run lint, test and build scripts and presist the project folder
  backend_build_test :
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Installing Main dependencies
          command: |
            npm install   
      - run:
          name: Installing Backend dependencies
          command: |
            npm run backend:install   
      - run:
          name: Linting
          command: |
            npm run backend:lint
      - run:
          name: App Build
          command: |
            npm run backend:build
      - run:
          name: Jasmine Tests
          command: |
            npm run backend:test
      - persist_to_workspace:
          root: .
          paths:
            - ./*

#Deploy backend code to elastic beanstalk staging environment
  deploy_backend_staging:
    docker:
      - image: "cimg/base:stable"
    steps:
      - attach_workspace:
          at: ./
      - aws-eb/setup
      - run:
          name: App Deploy
          command: |
            cd backend
            eb setenv env=staging DATABEASE_HOST=$DATABEASE_HOST DATABASE_NAME=$DATABASE_NAME DATABASE_USER=$DATABASE_USER DATABASE_PWD=$DATABASE_PWD DATABASE_PORT=$DATABASE_PORT DATABASE_NAME_TEST=$DATABASE_NAME_TEST BCRYPT_PWD=$BCRYPT_PWD SALT_ROUNDS=$SALT_ROUNDS JWT_SECRET=$JWT_SECRET
            eb init -p "Node.js 16 running on 64bit Amazon Linux 2" --region us-east-1 udacity-storefront-backend
            eb deploy udacity-storefront-backend-staging
            eb status

#Deploy backend code to elastic beanstalk production environment
  deploy_backend_prod:
    docker:
      - image: "cimg/base:stable"
    steps:
      - attach_workspace:
          at: ./
      - aws-eb/setup
      - run:
          name: App Deploy
          command: |
            cd backend
            eb setenv env=prod DATABEASE_HOST=$DATABEASE_HOST DATABASE_NAME=$DATABASE_NAME DATABASE_USER=$DATABASE_USER DATABASE_PWD=$DATABASE_PWD DATABASE_PORT=$DATABASE_PORT DATABASE_NAME_TEST=$DATABASE_NAME_TEST BCRYPT_PWD=$BCRYPT_PWD SALT_ROUNDS=$SALT_ROUNDS JWT_SECRET=$JWT_SECRET
            eb init -p "Node.js 16 running on 64bit Amazon Linux 2" --region us-east-1 udacity-storefront-backend
            eb deploy udacity-storefront-backend-prod
            eb status

#Deploy frontend code to s3 staging bucket
  deploy_frontend_staging:
    docker:
      - image: "cimg/base:stable"
    steps:
      - attach_workspace:
          at: ./
      - node/install
      - aws-cli/setup
      - run:
          name: App Deploy
          command: |
            npm run frontend:deploy_staging

#Deploy frontend code to s3 production bucket
  deploy_frontend_prod:
    docker:
      - image: "cimg/base:stable"
    steps:
      - attach_workspace:
          at: ./
      - node/install
      - aws-cli/setup
      - run:
          name: App Deploy
          command: |
            npm run frontend:deploy_prod

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - frontend_build_test
      - backend_build_test
      - deploy_frontend_staging:
          requires:
            - frontend_build_test
      - deploy_backend_staging:
          requires:
            - backend_build_test
      - frontend_deployment_approval:
          type: approval
          requires:
            - deploy_frontend_staging
      - backend_deployment_approval:
          type: approval
          requires:
            - deploy_backend_staging
      - deploy_frontend_prod:
          requires:
            - frontend_deployment_approval 
      - deploy_backend_prod:
          requires:
            - backend_deployment_approval 